Repository vissimo-group/chardonnay, pull requests merged in 2024-01, with the labels that each got.

#9 TEC-4137: Side Panel Component
  .eslintrc.js
  package-lock.json
  package.json
  src/components/SidePanel/SidePanel.stories.tsx
  src/components/SidePanel/SidePanelClose/index.tsx
  src/components/SidePanel/SidePanelClose/style.tsx
  src/components/SidePanel/SidePanelClose/type.ts
  src/components/SidePanel/SidePanelContent/index.tsx
  src/components/SidePanel/SidePanelContent/style.tsx
  src/components/SidePanel/SidePanelContent/types.ts
  src/components/SidePanel/SidePanelOverlay/index.tsx
  src/components/SidePanel/SidePanelOverlay/style.tsx
  src/components/SidePanel/SidePanelRoot/index.tsx
  src/components/SidePanel/SidePanelRoot/type.ts
  src/components/SidePanel/SidePanelTrigger/index.tsx
  src/components/SidePanel/SidePanelTrigger/style.tsx
  src/components/SidePanel/SidePanelTrigger/type.ts
  src/components/SidePanel/index.tsx
  src/components/index.ts
  src/contexts/SidePanel/context.tsx
  src/contexts/SidePanel/index.tsx
  src/contexts/SidePanel/type.ts
  src/index.ts
  tsconfig.json
  vite.config.ts
  vitest.setup.ts
Labels: enhancement

#10 TEC-4211: Flow circle ci to GitHub
  .circleci/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy-docs.yml
  .github/workflows/deploy-github-pages.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/test.yml
  .storybook/manager-head.html
  package.json
Labels: enhancement

#11 TEC-4190: Checkbox and Selector components
  public/caret-down.svg
  public/check.svg
  src/components/Checkbox/Checkbox.stories.tsx
  src/components/Checkbox/index.tsx
  src/components/Checkbox/style.tsx
  src/components/Checkbox/types.ts
  src/components/Select/Select.stories.tsx
  src/components/Select/index.tsx
  src/components/Select/style.tsx
  src/components/Select/types.ts
  src/components/index.ts
  src/index.ts
Labels: enhancement

#8 TEC-4134: Delivery method selector
  src/components/Border/Border.stories.tsx
  src/components/Border/index.tsx
  src/components/Border/style.tsx
  src/components/Border/type.ts
  src/components/Card/Card.stories.tsx
  src/components/Card/index.tsx
  src/components/Card/style.tsx
  src/components/Card/type.ts
  src/components/CardAddress/index.tsx
  src/components/Line/Line.stories.tsx
  src/components/Line/index.tsx
  src/components/Line/style.tsx
  src/components/Line/type.ts
  src/components/Radio/Radio.stories.tsx
  src/components/Radio/index.tsx
  src/components/Radio/style.tsx
  src/components/Radio/type.ts
  src/components/SelectListType/SelectListAction/index.tsx
  src/components/SelectListType/SelectListAction/style.tsx
  src/components/SelectListType/SelectListAction/type.ts
  src/components/SelectListType/SelectListPrice/index.tsx
  src/components/SelectListType/SelectListPrice/type.ts
  src/components/SelectListType/SelectListRadio/index.tsx
  src/components/SelectListType/SelectListRadio/type.ts
  src/components/SelectListType/SelectListRoot/index.tsx
  src/components/SelectListType/SelectListRoot/type.ts
  src/components/SelectListType/SelectListSubTitle/index.tsx
  src/components/SelectListType/SelectListSubTitle/type.ts
  src/components/SelectListType/SelectListTitle/index.tsx
  src/components/SelectListType/SelectListTitle/type.ts
  src/components/SelectListType/SelectListType.stories.tsx
  src/components/SelectListType/index.ts
  src/components/Text/Text.stories.tsx
  src/components/Text/index.tsx
  src/components/Text/type.ts
  src/components/index.ts
  src/index.ts
Labels: enhancement

#7 TEC-4140: Coupon related components
  package.json
  src/components/Collapsible/CollapsibleContent/index.tsx
  src/components/Collapsible/CollapsibleContent/style.tsx
  src/components/Collapsible/CollapsibleContent/types.ts
  src/components/Collapsible/CollapsibleRoot/index.tsx
  src/components/Collapsible/CollapsibleRoot/types.ts
  src/components/Collapsible/CollapsibleTrigger/index.tsx
  src/components/Collapsible/CollapsibleTrigger/styles.ts
  src/components/Collapsible/CollapsibleTrigger/types.ts
  src/components/Collapsible/index.ts
  src/components/index.ts
  src/contexts/CollapsibleContext/index.tsx
  src/contexts/CollapsibleContext/types.ts
  src/index.ts
  src/stories/Collapsible.stories.tsx
Labels: enhancement

#13 TEC-4233: Fix TopBar Tag component color
  src/components/Tag/index.tsx
Labels: publish_docs

#5 TEC-4133: Delivery components selected address
  .circleci/config.yml
  package.json
  src/components/Border/style.tsx
  src/components/Button/index.test.ts
  src/components/CardAddress/Select/index.tsx
  src/components/CardAddress/Shipping/index.tsx
  src/components/CardAddress/index.tsx
  src/components/TopBar/index.test.ts
  src/components/index.ts
  src/index.ts
  src/stories/SelectAddress.stories.tsx
  src/stories/ShippingAddress.stories.tsx
Labels: enhancement, publish_docs

#14 TEC-4263: Downgrade styled-component
  .circleci/config.yml
  package.json
  src/components/SidePanel/SidePanel.stories.tsx
  src/components/Text/index.tsx
  src/components/Text/type.ts
Labels: bug
