Repository vissimo-group/chardonnay, pull requests merged in 2024-03, with the labels that each got.

#19 TEC-4171: FreeShippingProgress component
  package.json
  src/components/FreeShippingProgress/FormattedShippingMessage/index.spec.tsx
  src/components/FreeShippingProgress/FormattedShippingMessage/index.stories.tsx
  src/components/FreeShippingProgress/FormattedShippingMessage/index.tsx
  src/components/FreeShippingProgress/FormattedShippingMessage/style.tsx
  src/components/FreeShippingProgress/FormattedShippingMessage/type.ts
  src/components/FreeShippingProgress/FreeShippingProgressBar/index.stories.tsx
  src/components/FreeShippingProgress/FreeShippingProgressBar/index.tsx
  src/components/FreeShippingProgress/FreeShippingProgressBar/styles.tsx
  src/components/FreeShippingProgress/FreeShippingProgressBar/type.ts
  src/components/FreeShippingProgress/FreeShippingProgressRoot/index.stories.tsx
  src/components/FreeShippingProgress/FreeShippingProgressRoot/index.tsx
  src/components/FreeShippingProgress/FreeShippingProgressRoot/style.tsx
  src/components/FreeShippingProgress/FreeShippingProgressRoot/type.ts
  src/components/FreeShippingProgress/index.tsx
  src/components/index.ts
  src/index.ts
Labels: enhancement, publish_docs

#22 TEC-4356: Adjustments on wizard component
  package.json
  src/components/Wizard/WizardItem/WizardItemLabel/index.stories.tsx
  src/components/Wizard/WizardItem/WizardItemLabel/index.tsx
  src/components/Wizard/WizardItem/WizardItemLabel/style.tsx
  src/components/Wizard/WizardItem/WizardItemLabel/type.ts
  src/components/Wizard/WizardItem/WizardItemPoint/index.stories.tsx
  src/components/Wizard/WizardItem/WizardItemPoint/index.tsx
  src/components/Wizard/WizardItem/WizardItemPoint/style.tsx
  src/components/Wizard/WizardItem/WizardItemPoint/type.ts
  src/components/Wizard/WizardItem/WizardItemRoot/style.tsx
  src/components/Wizard/WizardProgressBar/WizardProgressBar.stories.tsx
  src/components/Wizard/WizardProgressBar/index.tsx
  src/components/Wizard/WizardProgressBar/style.tsx
  src/components/Wizard/WizardProgressBar/type.ts
Labels: enhancement, publish_docs

#20 TEC-4136: ModalAddressCard
  src/components/CardAddress/ModalAddressCard/ModalAddressCard.stories.tsx
  src/components/CardAddress/ModalAddressCard/ModalAddressCardAction/index.tsx
  src/components/CardAddress/ModalAddressCard/ModalAddressCardAction/style.tsx
  src/components/CardAddress/ModalAddressCard/ModalAddressCardAction/type.ts
  src/components/CardAddress/ModalAddressCard/ModalAddressCardComplement/index.tsx
  src/components/CardAddress/ModalAddressCard/ModalAddressCardComplement/style.tsx
  src/components/CardAddress/ModalAddressCard/ModalAddressCardContent/index.tsx
  src/components/CardAddress/ModalAddressCard/ModalAddressCardContent/style.tsx
  src/components/CardAddress/ModalAddressCard/ModalAddressCardIcon/index.tsx
  src/components/CardAddress/ModalAddressCard/ModalAddressCardIcon/style.tsx
  src/components/CardAddress/ModalAddressCard/ModalAddressCardRoot/index.tsx
  src/components/CardAddress/ModalAddressCard/ModalAddressCardRoot/style.tsx
  src/components/CardAddress/ModalAddressCard/ModalAddressCardRoot/type.ts
  src/components/CardAddress/ModalAddressCard/ModalAddressCardTitle/index.tsx
  src/components/CardAddress/ModalAddressCard/ModalAddressCardTitle/style.tsx
  src/components/CardAddress/ModalAddressCard/index.ts
  src/components/CardAddress/ModalAddressCard/type.ts
  src/components/CardAddress/Select/SelectAddress.stories.tsx
  src/components/CardAddress/Shipping/ShippingAddress.stories.tsx
  src/components/index.ts
  src/index.ts
Labels: enhancement

#23 TEC-4373: Improvements and changes needed in DS for step 2
  package.json
  src/components/CardAddress/Select/index.tsx
  src/components/CardAddress/Shipping/index.tsx
  src/components/Input/index.tsx
  src/components/Input/mask.ts
  src/components/Input/style.tsx
  src/components/Input/types.ts
  src/components/Select/Select.stories.tsx
  src/components/Select/index.tsx
  src/components/Select/style.tsx
  src/components/SidePanel/SidePanelContent/style.tsx
  src/components/SidePanel/SidePanelContent/types.ts
  src/components/SidePanel/SidePanelOverlay/index.tsx
  src/components/SidePanel/SidePanelOverlay/style.tsx
  src/index.ts
Labels: enhancement

#25 TEC-4379: Fix button type prop
  package.json
  src/components/Button/index.stories.tsx
  src/components/Button/index.tsx
  src/components/Button/style.tsx
  src/components/Button/type.ts
Labels: bug, publish_docs
